### ISSUE TITLE
Unable to execute Java 8 unit tests when "java.home" is set to Java 11 and "java.configuration.runtimes" set to Java 8.

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode-java-test#1111]
Per https://github.com/redhat-developer/vscode-java/issues/1543, I have set it up so that the Debugger for Java uses Java 11 SDK, and execute Java 8 code. With this new setup, I'm able to continue debugging and running Java 8 code while the extensions are using Java 11, which is the recommended option given in that linked issue.

However, when it comes to testing unit tests, I cannot run and debug the unit tests in Java 8. It would throw an error exception of the given following, which is expecting for the missing `com.sun.tools.jar` library that Java 8 SDK still has, but not in Java 11 SDK:

```
Execution compile_with_aspectj of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:11.0.8 at specified path /home/nintendo/Apps/AdoptOpenJDK/jdk-11.0.8+10/../lib/tools.jar (org.codehaus.mojo:aspectj-maven-plugin:1.11:compile:compile_with_aspectj:compile)

org.apache.maven.plugin.PluginExecutionException: Execution compile_with_aspectj of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:11.0.8 at specified path /home/nintendo/Apps/AdoptOpenJDK/jdk-11.0.8+10/../lib/tools.jar
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1378)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:11.0.8 at specified path /home/nintendo/Apps/AdoptOpenJDK/jdk-11.0.8+10/../lib/tools.jar
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:221)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:152)
	at org.eclipse.m2e.core.internal.project.registry.EclipsePluginDependenciesResolver.resolve(EclipsePluginDependenciesResolver.java:61)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:404)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:374)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:234)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
	... 30 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.sun:tools:jar:11.0.8 at specified path /home/nintendo/Apps/AdoptOpenJDK/jdk-11.0.8+10/../lib/tools.jar
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:213)
	... 36 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.sun:tools:jar:11.0.8 at specified path /home/nintendo/Apps/AdoptOpenJDK/jdk-11.0.8+10/../lib/tools.jar
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:266)
	... 39 more

```

There aren't any options for me to be able to set it so that it can launch the unit tests with Java 11 (because the extensions need Java 11), while keeping the unit tests running in Java 8 at runtime.

What can I do to mitigate this, and how should I solve this issue?

**Comment by jdneo** [comment]
Wired, from my understanding, test runner won't select the java runtime, it just resolve the debug configuration and pass it the the Java Debugger.

Is it possible for you to share a sample project to repro this issue? I can take a look at what's happening there.

**Comment by tommai78101** [comment]
@jdneo Sorry, the original error occurred from a commerical production codebase, so I can't share it, and went to create a sample project instead. Your comment, about how the debug/launch configuration is just passing through from the test runner to the Java debugger, did helped me point towards a solution. I realized later on that something else might be causing the unexplained error that might not be related to the vscode-java-test extension.

The error occurred whenever it encounters an error that's caused by a misconfigured Maven project, or when it just hits any error exceptions at any given point in time. That's when it threw out the exception error.

As you can see in the image below, our unit test works fine, despite the errors being logged:

![image](https://user-images.githubusercontent.com/6444116/100766147-522aa600-33c6-11eb-8887-5ff200678c9b.png)

So I was able to proceed with my work.

**Comment by jdneo** [comment]
Seems the problem is solved. Can I close this issue?

**Comment by tommai78101** [comment]
Sorry, yes. I'll do it.

**Comment by jdneo** [comment]
Thanks!
