### ISSUE TITLE
vscode-java-test causes server crash (NPE)

### ISSUE THREAD

**Issue by astrelsky** [microsoft/vscode-java-test#1219]
Appears to be due to a missing dependency. My project currently does not have any tests and this is preventing the language server from starting. Here is the first stack trace, see the attached log for more details.

vscode:
Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

vscjava.vscode-java-test v0.30.0

<details><summary>stacktrace</summary>

```
!SESSION 2021-06-26 09:30:49.133 -----------------------------------------------
eclipse.buildId=unknown
java.version=15.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -data c:\Users\astre\AppData\Roaming\Code\User\workspaceStorage\1250e9efa6886007aaf5bfbed1661478\redhat.java\jdt_ws

!ENTRY com.microsoft.java.test.plugin 4 0 2021-06-26 09:30:51.244
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [144]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit4.runtime

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:459)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```
</details>

[log.txt](https://github.com/microsoft/vscode-java-test/files/6720176/log.txt)

**Comment by jdneo** [comment]
@astrelsky Could you please try:

1. Clean the global cache, which locates at `C:\Users\<user name>\AppData\Roaming\Code\User\globalStorage\redhat.java\<current version of your extension>`
2. Remove the test runner extension which locates at `C:\Users\<user name>\.vscode\extensions\vscjava.vscode-java-test-xxx`
3. Reinstall the test runner extension

**Comment by astrelsky** [comment]
Sure. I will give it a  shot tonight and report back.

**Comment by astrelsky** [comment]
> 2\. C:\Users\<user name>\.vscode\extensions

It seems to be ok now. If for any reason I missed something and it occurs again I will reopen this ticket.
