### ISSUE TITLE
Cannot add command line arguments via java.test.config

### ISSUE THREAD

**Issue by cgillum018** [microsoft/vscode-java-test#1297]
I'm trying to add listeners when running testNG tests using the Java Test runner.

In my settings.xml I've added:

"java.test.config": {
      "name": "RunWithContinue",
      "workingDirectory": "${workspaceFolder}",
      "args": [
        "-listener", "org.test.TestFilter"
      ]
    },

But when I run:

[ERROR] {"name":"error","attributes":{"message":"Failed to run TestNG tests","trace":"java.lang.ClassNotFoundException: -listener
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.microsoft.java.test.runner.testng.TestNGLauncher.getClassName(TestNGLauncher.java:53)
        at com.microsoft.java.test.runner.testng.TestNGLauncher.parse(TestNGLauncher.java:46)
        at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:32)
        at com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)
"}}

It seems all args are expected to be a Class/Method name, even though it seems to be the only place to pass TestNG command line arguments:

![image](https://user-images.githubusercontent.com/78982493/132441971-f5a4999a-c419-405f-ac02-d750deec0e7b.png)

Is there a workaround?

**Comment by jdneo** [comment]
Hi @cgillum018, currently the TestNG runner in this extension is a customized one. So the usage might be different from the `TestNG command line arguments`.

I think we need to migrate to https://github.com/testng-team/testng-remote to solve this.

**Comment by piotrpalek** [comment]
I'm running into the same issue, is there some workaround or base config I could copy?

**Comment by ThomasH-75** [comment]
I also ran into this issue, when moving from Eclipse to VSCode.

As a workaround I use the Service Loader mechanism to include my listener.
https://testng.org/testng_listeners.html#_specifying_listeners_with_serviceloader
