### ISSUE TITLE
False green test

### ISSUE THREAD

**Issue by supersonicclay** [Microsoft/vscode-java-test#130]
I found a scenario using [mockito](http://site.mockito.org/) where this plugin gives a false green result (i.e. says the test passed when in fact, it threw an exception).

## Repro:

```java
package mytests;

import org.junit.Test;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.*;
import java.util.List;

public class SimpleTest {

    @Test
    public void shouldFail() throws Exception {
        List myMock = mock(List.class);

        MyClass value = new MyClass("one");

        myMock.add(value);

        verify(myMock).add(new MyClass("two")); // this throws an exception, but doesn't fail the test
        fail(); // this never gets called
    }

    class MyClass {
        MyClass(String value) { }
    }
}
```

## Actual result:

* Green result in VS Code

## Expected result:

* Red result in VS Code with exception that arguments are different (similar to `mvn test` run).

## Note

Running `mvn test` produces the desired exception:

```
Argument(s) are different! Wanted:
list.add(
    mytests.SimpleTest$MyClass@574059d5
);
-> at mytests.SimpleTest.shouldFail(SimpleTest.java:21)
Actual invocation has different arguments:
list.add(
    mytests.SimpleTest$MyClass@6d672bd4
);
-> at mytests.SimpleTest.shouldFail(SimpleTest.java:19)
```

**Comment by ansyral** [comment]
@supersonicclay  thanks for reporting this, it is a bug, the test actually failed.
