### ISSUE TITLE
Running test of file compiled with Maven / Java 11 produces java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by ryno1234** [microsoft/vscode-java-test#1305]
I haven't seen anyone else post this issue so I'm wondering if I have a configuration problem. 

I have compiled my multi-module Maven project targeting Java 11. While within VS Code, attempts to run a test file's test produces the following error:

```
java.lang.UnsupportedClassVersionError: com/myapp/service/MyServiceImplTest has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:766)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:490)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

All of my VS Code settings and launch file configurations do not specify an explicit JDK version and I have confirmed that VS Code is launching and utilizing Java 11, not 8.

Why does my test runner run in a Java 8 context?

**Comment by jdneo** [comment]
Would you mind to share a sample project for this issue? I can try it on my side to see what's going on.

**Comment by ryno1234** [comment]
It might be easier for me to ask what determines what version of the java runtime that is launched during test execution? I've confirmed in my task manager in Windows that 1.8 is launched when I execute a test.

What is the switch for this?

**Comment by jdneo** [comment]
It's determined by the Java Language Server.

There is a setting called `java.configuration.runtimes` that maps the jdk versions to the installation location on your machine.

Any for example, let's say you are using Maven for your project, and set the Java version to 11. Then, the Java Language Server will automatically pick the matchest JDK to launch it.

**Comment by ryno1234** [comment]
Ah - Ok. So my issue is with my configuration as it relates to the Java Language Server. That's what I thought after further investigation myself. I posted my question over there: https://github.com/microsoft/vscode-java-pack/issues/750

**Comment by ryno1234** [comment]
**SOLVED:** For anyone landing here through search, my issue was the Java Language Server was not correctly picking up my target Java version as configured in my Maven pom.xml. This was able to be confirmed via the `Configure Java Runtime` screen accessible by pressing `ctrl` + `shift` + `p` to access the command pallet and entering "Java: Configure Java Runtime".

To fix this, I needed to execute a "Java: Clean Java Language Server Workspace" command. After completing that, all my projects correctly had their Java versions identified.

**Comment by jdneo** [comment]
Thank you @ryno1234 for providing the detailed information!

Closing this issue since it's been resolved.
