### ISSUE TITLE
Use arthas-memorycompiler dynamic compile class run test error

### ISSUE THREAD

**Issue by zzq0324** [microsoft/vscode-java-test#1306]
### Environment

* VSCode version: Version: 1.60.1 (Universal)
* Operating System version: macOS 10.15.7
* Java Runtime :  JDK 1.8

### Steps to reproduce this issue

1. `pom.xml` add `arthas-memorycompiler` dependency
```xml
<dependencies>
  <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>4.3.30.RELEASE</version>
  </dependency>

  <dependency>
      <groupId>com.taobao.arthas</groupId>
      <artifactId>arthas-memorycompiler</artifactId>
      <version>3.5.4</version>
  </dependency>

  <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.32</version>
  </dependency>

  <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
  </dependency>

  <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-test</artifactId>
      <version>4.3.30.RELEASE</version>
      <scope>test</scope>
  </dependency>
</dependencies>
```
2. Test Class
```java
import java.io.IOException;
import java.util.Map;

import com.taobao.arthas.compiler.DynamicCompiler;

import org.junit.Test;

public class CompileTest {
    @Test
    public void test() throws ClassNotFoundException, IOException {
        runCompile();
    }

    public static void main(String[] args) throws IOException {
        runCompile();
    }

    private static void runCompile() {
        String className = "test.Hello";
        String code = "public class Hello{public static void main(String[] args) {System.out.println(\"Hello\");}};";
        String successCode = "package test;" + code;
        Class type = compile(className, successCode);
        System.out.println("first: " + type.getName());

        // diff with successCode is add spring import
        String failCode = "package test;import org.springframework.beans.factory.annotation.Value;" + code;
        type = compile(className, failCode);
        System.out.println("second: " + type.getName());
    }

    private static Class compile(String className, String source) {
        DynamicCompiler dynamicCompiler = new DynamicCompiler(Thread.currentThread().getContextClassLoader());

        dynamicCompiler.addSource(className, source);

        Map<String, Class<?>> classMap = dynamicCompiler.build();

        // Compile success ,return class
        if (dynamicCompiler.getErrors() == null || dynamicCompiler.getErrors().size() == 0) {
            return classMap.get(className);
        }

        throw new IllegalStateException("Compile error");
    }
}

```
3. run test
When I run with main method, it compile success;
when i run junit test with test method, it compile error. This is error stack trace: 

```java
Caused by: com.taobao.arthas.compiler.DynamicCompilerException: java.lang.RuntimeException: java.lang.RuntimeException: Wasn't able to open file:/Users/zhengzhq/Library/Application%20Support/Code/User/globalStorage/redhat.java/0.82.0/config_mac/org.eclipse.osgi/81/0/.cp/org as a jar file

 at com.taobao.arthas.compiler.DynamicCompiler.build(DynamicCompiler.java:89)

 at cn.zzq0324.feature.flag.support.JdkCompiler.compile(JdkCompiler.java:38)

 at cn.zzq0324.feature.flag.FeatureFlagInstanceRegister.compileAndLoadClass(FeatureFlagInstanceRegister.java:83)

 at cn.zzq0324.feature.flag.FeatureFlagInstanceRegister.dynamicLoadClassAndRegisterBean(FeatureFlagInstanceRegister.java:63)

 at cn.zzq0324.feature.flag.FeatureFlagInstanceRegister.registerIfNotExist(FeatureFlagInstanceRegister.java:39)

 ... 31 more

Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Wasn't able to open file:/Users/zhengzhq/Library/Application%20Support/Code/User/globalStorage/redhat.java/0.82.0/config_mac/org.eclipse.osgi/81/0/.cp/org as a jar file

 at com.sun.tools.javac.main.Main.compile(Main.java:559)

 at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)

 at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)

 at com.taobao.arthas.compiler.DynamicCompiler.build(DynamicCompiler.java:61)

 ... 35 more

Caused by: java.lang.RuntimeException: Wasn't able to open file:/Users/zhengzhq/Library/Application%20Support/Code/User/globalStorage/redhat.java/0.82.0/config_mac/org.eclipse.osgi/81/0/.cp/org as a jar file

 at com.taobao.arthas.compiler.PackageInternalsFinder.processJar(PackageInternalsFinder.java:88)

 at com.taobao.arthas.compiler.PackageInternalsFinder.listUnder(PackageInternalsFinder.java:62)

 at com.taobao.arthas.compiler.PackageInternalsFinder.find(PackageInternalsFinder.java:51)

 at com.taobao.arthas.compiler.DynamicJavaFileManager.list(DynamicJavaFileManager.java:81)

 at com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:231)

 at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2796)

 at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446)

 at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)

 at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)

 at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)

 at com.sun.tools.javac.code.Symbol$PackageSymbol.flags(Symbol.java:863)

 at com.sun.tools.javac.comp.Check.checkDeprecated(Check.java:3163)

 at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3635)

 at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3490)

 at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3233)

 at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)

 at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)

 at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)

 at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)

 at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)

 at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)

 at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)

 at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)

 at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)

 at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)

 at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)

 at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)

 at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)

 at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)

 at com.sun.tools.javac.comp.Attr.attribImportQualifier(Attr.java:410)

 at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:544)

 at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:571)

 at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)

 at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)

 at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:528)

 at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)

 at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)

 at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1038)

 at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)

 at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)

 at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)

 at com.sun.tools.javac.comp.Enter.main(Enter.java:471)

 at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)

 at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:857)

 at com.sun.tools.javac.main.Main.compile(Main.java:523)

 ... 38 more

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

 at java.lang.String.substring(String.java:1967)

 at com.taobao.arthas.compiler.PackageInternalsFinder.processJar(PackageInternalsFinder.java:69)

 ... 82 more
```

Pls help me, thank you!

**Comment by jdneo** [comment]
Could you let me know what's contained in

`/Users/zhengzhq/Library/Application%20Support/Code/User/globalStorage/redhat.java/0.82.0/config_mac/org.eclipse.osgi/81/0/.cp/`?

**Comment by zzq0324** [comment]
> Could you let me know what's contained in
> 
> `/Users/zhengzhq/Library/Application%20Support/Code/User/globalStorage/redhat.java/0.82.0/config_mac/org.eclipse.osgi/81/0/.cp/`?

It contains:
![image](https://user-images.githubusercontent.com/24889976/134164574-0237e4c5-c6a9-4c19-8577-51cfb3b95c0d.png)
![image](https://user-images.githubusercontent.com/24889976/134164633-c446a585-89ae-4a4d-b886-513e5df69ce7.png)

**Comment by jdneo** [comment]
That folder contains compiled class files instead of jar.

To me, it's more likely an issue of arthas-memorycompiler. I've no background information about it, so have no idea why it must be jars to be there.

**Comment by zzq0324** [comment]
Thank you @jdneo, I have submitted a pull requet to `arthas`, see [Bugfix: PackageInternalsFinder support file path with white space and chinese character](https://github.com/alibaba/arthas/pull/1921)
