### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IJavaElement.getElementType()"

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1397]
From https://github.com/microsoft/vscode-java-pack/issues/956

Error in calling delegate command handler.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IJavaElement.getElementType()" because "element" is null
	at org.eclipse.jdt.ls.core.internal.hover.JavaElementLabelComposer.appendElementLabel(JavaElementLabelComposer.java:154)
	at org.eclipse.jdt.ls.core.internal.hover.JavaElementLabels.getElementLabel(JavaElementLabels.java:376)
	at org.eclipse.jdt.ls.core.internal.hover.JavaElementLabels.getElementLabel(JavaElementLabels.java:364)
	at com.microsoft.java.test.plugin.util.TestItemUtils.constructJavaTestItem(TestItemUtils.java:56)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.findTestItemsInTypeBinding(TestSearchUtils.java:383)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.findTestTypesAndMethods(TestSearchUtils.java:360)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:60)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
```

**Comment by jdneo** [comment]
Fixed by https://github.com/microsoft/vscode-java-test/pull/1396
