### ISSUE TITLE
java.lang.IllegalArgumentException: Path must include project and resource name: /xxx

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#1398]
```
java.lang.IllegalArgumentException: Path must include project and resource name: /xxxxxxx
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2139)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at com.microsoft.java.test.plugin.util.ProjectTestUtils.parseTestSourcePathString(ProjectTestUtils.java:139)
	at com.microsoft.java.test.plugin.util.ProjectTestUtils.getTestSourcePaths(ProjectTestUtils.java:120)
	at com.microsoft.java.test.plugin.util.ProjectTestUtils.listTestSourcePaths(ProjectTestUtils.java:61)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:48)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
```

**Comment by jdneo** [comment]
To verify this issue:

- Prepare an Eclipse project, whose source code is located at project root. Sample project:
[eclipse-project.zip](https://github.com/microsoft/vscode-java-test/files/8537159/eclipse-project.zip)
 
- The test items can be found and run
- In the server log, there is no errors like `Path must include project and resource name: /xxxxxxx`

_// cc @testforstephen_

**Comment by testforstephen** [comment]
Opening the sampel project `eclipse-project` above in VS Code, it still cannot load such project well.

The language server throws the same error during workspace initialization, this exception is not related with tester runner, we have to fix it on JLS side.

```
!MESSAGE An internal error occurred during: "Initialize workspace".
!STACK 0
java.lang.IllegalArgumentException: Path must include project and resource name: /eclipse-project
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2139)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:414)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:276)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
