### ISSUE TITLE
Nested parameterized methods cannot be run with in-project classes as parameters.

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1409]
I have the following arrangement in one of my test files: (full project attached as Zip)

In the testing UI, 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/76812421/164243037-fd3e9302-faac-4118-b9da-8b4b634a9190.png">

, 
- running NestedClass runs both methods fine  
- Running testInput runs this method fine.
- running testCheckUser doesn't run this method.  which is the bug.

The stacktrace is also given.
  

```
package com.blah.servimpl;

import java.util.stream.Stream;

import com.blah.common.ProtoGenClass.User;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;


public class OuterClass{
    
    @Nested
    @TestInstance(Lifecycle.PER_CLASS)
    class NestedClass{
        private User user1 = null;
        
         
        @ParameterizedTest
        @MethodSource("users")
        public void testCheckUser(User user){
            System.out.println("testCheckUser");
        }
        
        Stream<Arguments> inputs(){
            return Stream.of(Arguments.of(new String("apple")));
        }
        
        @ParameterizedTest
        @MethodSource("inputs")
        public void testInput(String input){
            System.out.println("testInput");
        }
        
        Stream<Arguments> users(){
            return Stream.of(Arguments.of(user1));
        }
       
        
    }
}
```

<details>
  <summary>Stack Trace of failure</summary>
 

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:78)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.discover(DefaultLauncherSession.java:81)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:46)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.<init>(JUnit5TestReference.java:46)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createFilteredTest(JUnit5TestLoader.java:71)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:64)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:53)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.junit.platform.commons.JUnitException: MethodSelector [className = 'com.blah.servimpl.OuterClass$NestedClass', methodName = 'testCheckUser', methodParameterTypes = 'com.blah.common.ProtoGenClass.User'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 15 more
Caused by: org.junit.platform.commons.JUnitException: Failed to load parameter type [com.blah.common.ProtoGenClass.User] for method [testCheckUser] in class [com.blah.servimpl.OuterClass$NestedClass].
	at org.junit.platform.commons.util.ReflectionUtils.lambda$loadRequiredParameterType$24(ReflectionUtils.java:1318)
	at org.junit.platform.commons.function.Try$Failure.getOrThrow(Try.java:335)
	at org.junit.platform.commons.util.ReflectionUtils.loadRequiredParameterType(ReflectionUtils.java:1317)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$resolveParameterTypes$22(ReflectionUtils.java:1309)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at org.junit.platform.commons.util.ReflectionUtils.resolveParameterTypes(ReflectionUtils.java:1310)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:1298)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:167)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:149)
	at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:86)
	at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:73)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:146)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.blah.common.ProtoGenClass.User
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:829)
	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
	at org.junit.platform.commons.function.Try.of(Try.java:93)
	at org.junit.platform.commons.function.Try.call(Try.java:57)
	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:792)
	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:748)
	at org.junit.platform.commons.util.ReflectionUtils.loadRequiredParameterType(ReflectionUtils.java:1316)
	... 48 more
```
</details>

[demo.zip](https://github.com/microsoft/vscode-java-test/files/8521944/demo.zip)

**Comment by jdneo** [comment]
Looks like here: https://github.com/microsoft/vscode-java-test/blob/cbd21d41fccacfe8b3cf3353d1284511e5121d8a/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java#L173-L177

We should always get the binary name. Otherwise, the separator of inner type will be `.` instead of `$`

**Comment by matter-it-does** [comment]
@jdneo thanks for the fix. When will 0.36.0 be released?  I don't see a due date on the milestone..

**Comment by jdneo** [comment]
Stable channel release will be at the end of this month.

Pre-release channel should be released recently.

**Comment by jdneo** [comment]
@matter-it-does The fix is contained in the pre-release `v0.35.2022061102`

**Comment by matter-it-does** [comment]
@jdneo thanks! <3

**Comment by jdneo** [comment]
To verifier:

1. Download sample projects https://github.com/microsoft/vscode-java-test/files/8521944/demo.zip
2. Open it in VS Code
3. Verify the test `com.blah.servimpl.OuterClass$NestedClass#testCheckUser(User)` can be run
