### ISSUE TITLE
Tests cannot be launched

### ISSUE THREAD

**Issue by lucidfrontier45** [microsoft/vscode-java-test#1481]
# Environment
System : Windows10, WSL2, Debian 11
JDK: OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1)
Gradle:  7.4.2
VSCode: v1.70.2
redhat.java: v1.10.0
vscjava.vscode-java-test: v0.37.2022083002
vscjava.vscode-java-debug: v0.43.0

# Symptom

Test cannot be launched. The notification in the right bottom shows `Run Tests: Resolving launch configuration` forever

![image](https://user-images.githubusercontent.com/655305/187845557-4b65a05d-903c-44d6-8f7c-3f87b0b59e8b.png)

# How to reproduce

1. Create an `Application` project with `gradle init` .
2. Open the project folder with VSCode
3. Open `Testing` in the side panel.
4. right click `appHasAGreeting()` and choose `Run Test`.

# Notes

1. Running the `main` of the `App` class from VSCode works fine.
2. Running `gradle test` works fine.

**Comment by mishi321** [comment]
`!ENTRY com.microsoft.java.test.plugin 4 0 2022-09-01 15:19:00.734
!MESSAGE failed to resolve the classpath.
!STACK 0
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchConfigurationDelegate.getJUnitLaunchArguments(JUnitLaunchConfigurationDelegate.java:78)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:102)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:529)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "org.osgi.framework.Bundle.getHeaders()" because "bundle" is null
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.localURL(JUnitLaunchConfigurationDelegate.java:737)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.entryString(JUnitLaunchConfigurationDelegate.java:726)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:205)
	... 19 more
Root exception:
java.lang.NullPointerException: Cannot invoke "org.osgi.framework.Bundle.getHeaders()" because "bundle" is null
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.localURL(JUnitLaunchConfigurationDelegate.java:737)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate$ClasspathLocalizer.entryString(JUnitLaunchConfigurationDelegate.java:726)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchConfigurationDelegate.getJUnitLaunchArguments(JUnitLaunchConfigurationDelegate.java:78)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:102)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:529)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)`
The same to you.
File .log message is here.

**Comment by kaipaysen** [comment]
Same here.. stuck on "Resolving launch configurations".

System : Mac OS
JDK: OpenJDK Runtime Environment (build 17.0.1+12-39)
Gradle: 7.4.2
Maven: 3.8.5
redhat.java: v1.10.0
vscjava.vscode-java-test: v0.37.0
vscjava.vscode-java-debug: v0.43.0

**Comment by jdneo** [comment]
I'm working on a fix to this issue.

**Comment by jdneo** [comment]
For anyone encountered this issue, please install [vscode-java-test-0.37.2022090109.vsix.zip](https://github.com/microsoft/vscode-java-test/files/9468557/vscode-java-test-0.37.2022090109.vsix.zip) to see if the problem got fixed and let me know if it's possible.

I'll do some verification as well. If everything is fine, I'll plan a hotfix release tomorrow.

**Comment by kaipaysen** [comment]
> For anyone encountered this issue, please install [vscode-java-test-0.37.2022090109.vsix.zip](https://github.com/microsoft/vscode-java-test/files/9468557/vscode-java-test-0.37.2022090109.vsix.zip) to see if the problem got fixed and let me know if it's possible.
> 
> I'll do some verification as well. If everything is fine, I'll plan a hotfix release tomorrow.

Great, works on my machine. Thank you very much.

**Comment by pcantrell** [comment]
Encountering this bug as well — along with the ~50 students in a Java-based course for whom this bug is their introduction to both Java and VS Code. 😬 

I tried installing the vsix fix attached above, and got this when trying to run tests:

```
java.lang.NoClassDefFoundError: org/junit/platform/commons/util/ClassNamePatternFilterUtils
	at org.junit.platform.launcher.core.LauncherFactory.loadAndFilterTestExecutionListeners(LauncherFactory.java:191)
	at org.junit.platform.launcher.core.LauncherFactory.registerTestExecutionListeners(LauncherFactory.java:179)
	at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:137)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:37)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
NativeConstructorAccessorImpl.java:77
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
DelegatingConstructorAccessorImpl.java:45
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
Constructor.java:499
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
ReflectAccess.java:128
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
ReflectionFactory.java:347
	at java.base/java.lang.Class.newInstance(Class.java:645)
Class.java:645
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.util.ClassNamePatternFilterUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
BuiltinClassLoader.java:641
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
ClassLoaders.java:188
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
ClassLoader.java:520
	... 18 more
```

Downgrading both the Language Support for Java _and_ Test Runner for Java extensions to the previous release fixes the issue for me.

**Comment by pcantrell** [comment]
Confirmed error from vsix occurs even after completely uninstalling all Java and Gradle extensions, then doing a clean install.

I installed the vsix using:

    code --install-extension vscode-java-test-0.37.2022090109.vsix

Is that the correct method?

**Comment by lucidfrontier45** [comment]
@jdneo 

Thank you for the fix. I confirmed vscode-java-test-0.37.2022090109.vsix.zip fixed the problem.

**Comment by jdneo** [comment]
@pcantrell This is because we upgrade the bundled junit jupiter version, which has a breaking change start from 1.7.0.

What you need to do is add the dependency `org.junit.platform:junit-platform-commons` to your project.

See: https://stackoverflow.com/questions/61801256/exception-in-thread-main-java-lang-noclassdeffounderror-org-junit-platform-co

**Comment by jdneo** [comment]
`0.37.1` has been released, the problem should be gone with the latest version.

**Comment by pcantrell** [comment]
> This is because we upgrade the bundled junit jupiter version, which has a breaking change start from 1.7.0.

The `build.gradle` in the project in question pins Jupiter to an older version:

```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter', version: '5.6.+'
}
```

Shouldn’t this prevent that problem? Does the VS Code test runner simply ignore the JUnit version specified in the project file?

**Comment by pcantrell** [comment]
Replying to myself: No, I see from experimentation that pinning to an old version of JUnit Jupier in fact _causes_ the problem. Simply updating the Jupiter version number to `5.9.+` fixes the problem, without having to add the junit-platform-commons dependency.

It seems like a bug that vscode-java-test can’t run tests for projects that specify older JUnit versions. After all, the point of specifying a version is precisely to avoid future breakages like this. Should I file that as a new issue?

**Comment by jdneo** [comment]
@pcantrell Please check: https://bugs.eclipse.org/bugs/show_bug.cgi?id=569860

**Comment by pcantrell** [comment]
Thanks for the explanation. [This comment](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569860#c3) echoes my thoughts quite closely. This does seem like a fundamental philosophical problem.

Fortunately I can simply upgrade JUnit in the projects in question, but at the very least, better diagnostics here would be useful.

**Comment by jdneo** [comment]
The Gradle Test Delegation (both run and debug) has supported now.

To use this feature, you need to install the latest [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) and [Gradle for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) extension.

To delegate the tests to Gradle, you can set the default testing profile in Testing explorer:
![image](https://github.com/user-attachments/assets/f3e982e0-0340-461c-b6c4-c8c7fe9352f5)
![image](https://github.com/user-attachments/assets/e1a2693c-e6d7-425a-b7d5-6adf878f4ce3)

If you do not want to change the default testing profile, you can trigger an one-time execution via:
![image](https://github.com/user-attachments/assets/1c3f7478-b100-40cf-98c2-6f0357050209)
![image](https://github.com/user-attachments/assets/55fa017c-adb3-4c5a-bc81-55db63834773)
