### ISSUE TITLE
Extension not detect the updated code

### ISSUE THREAD

**Issue by dyuyang** [microsoft/vscode-java-test#1514]
When I modified the code in unit test, the extension didn't detect the change and still ran test based on the old code.

Task this as an example:
`Assert.assertEquals(1, 2);`
When I changed the code to:
`Assert.assertEquals(1, 1);`
The extenstion still told me that 1 shouldn't equal to 2.

Here is the log of vscode:

```
java.lang.IllegalAccessError: superclass access check failed: class com.xxxxxx (in unnamed module @0x280445ac) cannot access class com.sun.tools.javac.tree.TreeTranslator (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x280445ac
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

it seems that the package xxxxxx has conflict with jdk. But even after I removed the dependency of package xxxxxx, clean the java workspace cache and restart the java project, the log wouldn't change.

**Comment by jdneo** [comment]
Could you provide a sample project for this issue?
