### ISSUE TITLE
"Resolving launch configuration" while trying to run SpringBootTest

### ISSUE THREAD

**Issue by JokaJukka** [microsoft/vscode-java-test#1539]
When trying to run `@SpringBootTest` in my maven project, the "Resolving launch configuration..." shows up, but that's all - the tests never launch. Other regular JUnit tests work just fine.

Also, when I open the output tab, following can be found under the "Language support for Java" option:
```
[Error - 8:09:16 AM] Mar 1, 2023, 8:09:16 AM failed to resolve the classpath.
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchConfigurationDelegate.getJUnitLaunchArguments(JUnitLaunchConfigurationDelegate.java:78)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:102)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:559)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: org.eclipse.core.runtime.CoreException: The input type of the launch configuration does not exist
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.abort(JUnitLaunchConfigurationDelegate.java:784)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getTestTarget(JUnitLaunchConfigurationDelegate.java:778)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:164)
	... 19 more

[Trace - 8:09:16 AM] Received response 'workspace/executeCommand - (37)' in 6ms.
No result returned.
```

May be related to #1536, but just to be sure I've created a new issue. Running VSCode 1.75.1 on Arch Linux.

**Comment by jdneo** [comment]
Does this issue only happen in test runner `0.38.1`?

**Comment by JokaJukka** [comment]
I've also tried version `0.37.1` I think, but with same results. I can try again.

**Comment by JokaJukka** [comment]
Yep, same results, same error, even after cleaning the workspace:
```
[Error - 9:07:22 AM] Mar 1, 2023, 9:07:22 AM failed to resolve the classpath.
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchConfigurationDelegate.getJUnitLaunchArguments(JUnitLaunchConfigurationDelegate.java:78)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:102)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:559)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: org.eclipse.core.runtime.CoreException: The input type of the launch configuration does not exist
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.abort(JUnitLaunchConfigurationDelegate.java:784)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getTestTarget(JUnitLaunchConfigurationDelegate.java:778)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:164)
	... 19 more
```

**Comment by jdneo** [comment]
Thank you for the information.

I'm planning to fix https://github.com/microsoft/vscode-java-test/issues/1536 by better handling the error - show the error notification and stop the test session when error happens.

But I guess it will not help you launch your spring boot test. If your request is to launch those spring boot test in vs code, could you share a sample project then I can take a look what's the gap?

**Comment by JokaJukka** [comment]
Unfortunatelly, I cannot - part of the libs are shared only on school level. I've tried to launch tests in an example project in spring initalizr, and they worked just fine...

If I find the cause of this issue, I'll inform you.

**Comment by JokaJukka** [comment]
Okay, finally found out why the tests were not working - the classname of the test was different from the filename. Now I feel stupid.

**Comment by jdneo** [comment]
Ah, I see. It's a known issue: https://github.com/microsoft/vscode-java-test/issues/859.

Let's track it there.

**Comment by lauksas** [comment]
> Okay, finally found out why the tests were not working - the classname of the test was different from the filename. Now I feel stupid.

Don't feel stupid, you just helped me realizing that moving the file to a different package did not triggered the refactor, and also, there was no compilation error!
