### ISSUE TITLE
StackOverflowError in VSC

### ISSUE THREAD

**Issue by jchojnacka-tbscg** [microsoft/vscode-java-test#1586]
I am unable to run a single test, and the icon next to it is not visible at all. 

In output I have error:
`[Error - 10:37:16 AM] Jul 3, 2023, 10:37:16 AM An internal error occurred during: "Initialize Workspace".
null
java.lang.StackOverflowError
	at org.eclipse.aether.util.graph.manager.ClassicDependencyManager.getKey(ClassicDependencyManager.java:216)
	at org.eclipse.aether.util.graph.manager.ClassicDependencyManager.manageDependency(ClassicDependencyManager.java:154)`

**Comment by jdneo** [comment]
It should be an upstream issue: https://github.com/redhat-developer/vscode-java/issues/3085

I'll close this issue and let's track it in the above issue link.

Thanks!
