### ISSUE TITLE
com.microsoft.java.test.plugin needs to update against upcoming JDT-LS release

### ISSUE THREAD

**Issue by rgrunber** [microsoft/vscode-java-test#1610]
In https://github.com/eclipse-jdtls/eclipse.jdt.ls/commit/bae72c27c2b66cc39da085a5a461c25bfe8e14e5 we got rid of various duplicated classes. In particular `org.eclipse.jdt.ls.core.internal.hover.JavaElementLabels` -> `org.eclipse.jdt.internal.core.manipulation.JavaElementLabelsCore`. I think the extension just needs to update accordingly.

```
!ENTRY org.eclipse.jdt.ls.core 4 2 2023-09-20 10:51:20.850
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels
	at com.microsoft.java.test.plugin.model.builder.JavaTestItemBuilder.build(JavaTestItemBuilder.java:75)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.resolvePath(TestSearchUtils.java:486)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:62)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:613)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.hover.JavaElementLabels cannot be found by com.microsoft.java.test.plugin_0.39.1
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
```

**Comment by jdneo** [comment]
Thank you, it has been updated in https://github.com/microsoft/vscode-java-test/pull/1607/files. I'll schedule a release for that very soon.

**Comment by zenoli** [comment]
@jdneo can you say when approximately this will be merged? Jdtls v.1.28 is out and I am experiencing the issue described by @rgrunber currently.

**Comment by jdneo** [comment]
@zenoli It should already contained in `0.40.0`.

Are you using openvsx instead of VS Code marketplace?

**Comment by zenoli** [comment]
@jdneo oh your absolutely right, my bad.
May I ask why there is no more `.vsix` file provided in the github release page since v0.39.0?

**Comment by jdneo** [comment]
We don't put vsix to the release page now. Users can build on their own, you can refer to: https://github.com/microsoft/vscode-java-test/blob/main/.github/workflows/build.yml.
