### ISSUE TITLE
Can't successfully Run Test for Testng framework

### ISSUE THREAD

**Issue by SyedIbrahim95** [microsoft/vscode-java-test#1652]
{"name":"error","attributes":{"message":"Failed to run TestNG tests","trace":"java.lang.ClassNotFoundException: random.LoginTest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.microsoft.java.test.runner.testng.TestNGLauncher.getClassNameFromMethod(TestNGLauncher.java:57)
        at com.microsoft.java.test.runner.testng.TestNGLauncher.parse(TestNGLauncher.java:43)
        at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:32)
        at com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)
"}}

**Comment by jdneo** [comment]
Are you using code-server?
