### ISSUE TITLE
com.microsoft.java.test.plugin fails to resolve

### ISSUE THREAD

**Issue by rgrunber** [microsoft/vscode-java-test#1681]
This may result in a lot of functionality failing (pretty much anything that requires a delegate command into JDT-LS) :
```
2024-04-18 10:41:30.178 [error] Error: No delegateCommandHandler for vscode.java.test.get.testpath
	at /home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1104943
	at ie (/home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1105237)
	at /home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1100021
	at Immediate.<anonymous> (/home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1100041)
	at process.processImmediate (node:internal/timers:476:21)
2024-04-18 10:41:30.569 [error] Error: No delegateCommandHandler for vscode.java.test.findJavaProjects
	at /home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1104943
	at ie (/home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1105237)
	at /home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1100021
	at Immediate.<anonymous> (/home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1100041)
	at process.processImmediate (node:internal/timers:476:21) java.execute.workspaceCommand {"value":"redhat.java","_lower":"redhat.java"}
2024-04-18 10:41:31.572 [error] Error: No delegateCommandHandler for vscode.java.test.findJavaProjects
	at /home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1104943
	at ie (/home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1105237)
	at /home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1100021
	at Immediate.<anonymous> (/home/rgrunber/.vscode/extensions/redhat.java-1.30.2024041808-linux-x64/dist/extension.js:2:1100041)
	at process.processImmediate (node:internal/timers:476:21)
```

```
!ENTRY com.microsoft.java.test.plugin 4 0 2024-04-18 10:41:26.340
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [114]
  Unresolved requirement: Require-Bundle: org.jacoco.core; bundle-version="0.8.11"
    -> Bundle-SymbolicName: org.jacoco.core; bundle-version="0.8.11.202310140853"
       org.jacoco.core [113]
         Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.6.0,9.7.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1908)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

This probably started happening due to https://github.com/microsoft/vscode-java-test/pull/1637 (included in 0.41.0) .
The site plugin correctly generates a repo that includes ASM, but does not explicitly package it at https://github.com/microsoft/vscode-java-test/pull/1637/files#diff-d3475322bf69b30d58ad43bc602d72645bde4df99dba9302c5bbef6ca5bf8c31R29 .

CC: @jdneo

**Comment by NickJAllen** [comment]
I have this problem too

**Comment by jdneo** [comment]
Thank you for reporting this @rgrunber :)

the jls extension `1.29.0` has already embedded `org.objectweb.asm` with version `9.6`, and updated to `9.7` in `1.30.0`.

I'll bump the jacoco version then.

BTW, when will we release redhat.java@1.30?

**Comment by rgrunber** [comment]
> Thank you for reporting this @rgrunber :)
> 
> the jls extension `1.29.0` has already embedded `org.objectweb.asm` with version `9.6`, and updated to `9.7` in `1.30.0`.
> 
> I'll bump the jacoco version then.
> 
> BTW, when will we release redhat.java@1.30?

Right. I never checked if JDT-LS contained ASM. I guess the jacoco bump simplifies things a lot. I'm aiming for releasing this Thursday, assuming I can put the changelogs up for today (Tuesday).

**Comment by jdneo** [comment]
@rgrunber I see. I'll make a release for the test runner after that.

**Comment by jdneo** [comment]
The stable version 0.41.1 is also released.
