### ISSUE TITLE
VS Code does not recognize junit tests

### ISSUE THREAD

**Issue by siddhsql** [microsoft/vscode-java-test#1692]
I am following the steps at [this](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) page to run Junit5 tests with VS Code and Maven. I have these extensions installed:

<img width="339" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/127623723/675e3ab2-93b4-4f54-a900-8f5deb9e9dc8">
<img width="344" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/127623723/b60dc0cb-0f7a-4e5a-9cfb-0d69bd8614e9">
<img width="332" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/127623723/f46c46f8-993d-4289-9a05-d09e86eb0b95">

and my `pom.xml` has:

```
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>    
    <scope>test</scope>
</dependency>        
```

I have put my test classes in `src/test/java`. but VS Code does not detect JUNIT5 tests. the green "lenses" or "buttons" do not show up next to the tests. In one of the logs I could see:

```
Preview features enabled at an invalid source release level 21, preview can be enabled only at source level 22; code: 2098258
```

<img width="1014" alt="image" src="https://github.com/microsoft/vscode-java-test/assets/127623723/4ce15014-c345-4d64-a8f4-a622cac3a475">

and not sure if it is because of this.

related: https://github.com/Microsoft/vscode-java-test/issues/470

**Comment by siddhsql** [comment]
I did some search and came across mention of a `.classpath` file. I do not see such file anywhere in my project.

**Comment by jdneo** [comment]
@siddhsql What if you run `Java: Clean Java Language Server Workspace`

**Comment by siddhsql** [comment]
i have done that many times. same result.

**Comment by jdneo** [comment]
Would you mind sharing the project to us?

**Comment by siddhsql** [comment]
i am not able to do that. it is a big project with many modules.

**Comment by diegoxxc14** [comment]
Hi, I solved this problem in JAVA PROJECTS, Clean Workspace. Then the green buttons are displayed in tests.
![image](https://github.com/microsoft/vscode-java-test/assets/41596984/038b7bad-f5c6-4349-b1cf-d3783e3ba431)

**Comment by siddhsql** [comment]
it does not work for me though. i have tried cleaning the workspace many
times.

**Comment by jdneo** [comment]
@siddhsql Does your problem resolved now?

**Comment by jdneo** [comment]
There is an undergoing effort about support running test in gradle build server: https://github.com/microsoft/build-server-for-gradle/pull/144

Once Once it's done, I'll check how to integrate that into the test runner extension.

**Comment by aisong** [comment]
@jdneo 我遇到了同样的问题。

执行mvn test-compile -f 可以编译成功。但是在vscode里面找不到测试类。
更加有问题的是，ide似乎不识别test下面的java类，语法错误不会提示。

source action：
![WX20240530-141142@2x](https://github.com/microsoft/vscode-java-test/assets/8147898/15de16d2-0049-4f4f-a49f-dab9fae5e6d1)

testing：
![WX20240530-141226@2x](https://github.com/microsoft/vscode-java-test/assets/8147898/227f64bb-10a1-491d-adaa-7c280955fa61)

清除目录、clear workspace都重复了很多次，都不解决问题。

能麻烦看下可能是什么问题导致？

**Comment by jdneo** [comment]
@aisong Could you share a sample project for your issue?

**Comment by aisong** [comment]
> @aisong Could you share a sample project for your issue?

业务系统的代码，不好直接发这里呀。🥲

**Comment by aisong** [comment]
我觉得是test目录的识别有问题，没有被正确识别为java sources。

虽然classpath的配置是正确的：
![WX20240530-150118@2x](https://github.com/microsoft/vscode-java-test/assets/8147898/c4d15ae7-2f4f-4d26-8e70-d541d44df3a8)

但因为某种原因，ide没有把src/test/java识别为源文件。

查看执行文件，里面只有classes，没有包含test-classes：
![WX20240530-150636@2x](https://github.com/microsoft/vscode-java-test/assets/8147898/21acb077-7874-46e5-a9e1-2210322ac60d)

**Comment by jdneo** [comment]
@aisong Have you set `java.import.maven.disableTestClasspathFlag`

**Comment by aisong** [comment]
> @aisong Have you set `java.import.maven.disableTestClasspathFlag`

not set.

**Comment by siddhsql** [comment]
no my problem is not solved. i don't use gradle. i am using maven with junit 5. thanks.

**Comment by siddhsql** [comment]
this is an unrelated question but does anyone know where does VS Code store the compiled classes? there is a `target` folder but its meant for use by Maven. Does VS Code overwrite the files in that folder with its compiled code?

**Comment by jdneo** [comment]
> Does VS Code overwrite the files in that folder with its compiled code? 

Yes

> is it possible to designate a different folder for vs code so that it does not interfere with maven?

This is a known issue: https://github.com/redhat-developer/vscode-java/issues/314

**Comment by aisong** [comment]
@jdneo 我终于找到我这里的问题出在哪里。但不知道为什么会这样。

在我的pom中引入了一个本地仓库的依赖，如果去掉它，ide会正常，如果引入它就会出现问题。
我打开了trace日志，截取了当在pom中引入这个依赖后出现的错误日志，请见附件。
[vscode-java.log](https://github.com/user-attachments/files/15507445/vscode-java.log)

能否从日志中判断出具体是什么问题？

**Comment by jdneo** [comment]
@aisong, thank you! Tracked at https://github.com/microsoft/vscode-java-test/issues/1693. Will investigate.

**Comment by aisong** [comment]
> @aisong, thank you! Tracked at #1693. Will investigate.

好的。看起来是读取依赖的信息时有报错。是依赖包中的文件缺失了什么必要信息么。还没找到解决办法。

**Comment by siddhsql** [comment]
> redhat-developer/vscode-java#314

this seems like a serious issue to me and am surprised its not fixed even after 7 years.

**Comment by ezrealliu** [comment]
@siddhsql  I also came across the same problem,  but, I resolved this problem by adding a .classpath file.  Sometimes, VSC cannot detect src\java\test as test source folder automatically( i don't know why ). You can enhance it by adding a .classpath file to tell vsc which folder should regarded as test source folder.

**Comment by siddhsql** [comment]
Hi Simon, thanks. could you elaborate please with more details?

**Comment by 18259008878** [comment]
![Image](https://github.com/user-attachments/assets/d3cb35d5-ae12-4020-a3c4-fbedcafcd813)
Try this.

**Comment by caohenghui** [comment]
> ![Image](https://github.com/user-attachments/assets/d3cb35d5-ae12-4020-a3c4-fbedcafcd813) Try this.

try了，木用

**Comment by CoderL98** [comment]
我也是突然扫描不到test了

![Image](https://github.com/user-attachments/assets/f8bb7b48-52d6-480f-bf69-5790691493dd)

**Comment by iHowCool** [comment]
我的Test图标也没有，我发现启动的时候有如下的报错。

<img width="271" alt="Image" src="https://github.com/user-attachments/assets/7a3b073c-3304-42e6-8b50-42f7f1c59948" />


[Error - 15:48:16] 2025年4月3日 15:48:15 FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [117]
  Unresolved requirement: Require-Bundle: org.jacoco.core; bundle-version="0.8.12"
    -> Bundle-SymbolicName: org.jacoco.core; bundle-version="0.8.12.202403310830"
       org.jacoco.core [116]
         Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.7.0,9.8.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:495)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2111)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:146)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2102)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2042)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:2004)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1916)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)

**Comment by iHowCool** [comment]
> 我的Test图标也没有，我发现启动的时候有如下的报错。
> 
> <img alt="Image" width="271" src="https://private-user-images.githubusercontent.com/98109964/429837298-7a3b073c-3304-42e6-8b50-42f7f1c59948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2NjY5MzIsIm5iZiI6MTc0MzY2NjYzMiwicGF0aCI6Ii85ODEwOTk2NC80Mjk4MzcyOTgtN2EzYjA3M2MtMzMwNC00MmU2LThiNTAtNDJmN2YxYzU5OTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAzVDA3NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjhjODk4OTQ1MDdlMjIxODUyYmQzMGRlNjM4NjI5YzJlNzJjZDRlNWI4N2U5MDY0MzNjYTU2MDQ0NWFjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.emO1Acm3SlqcNS14CbwGK-8Y5ZZEEzucrgvVbkB-z0M">
> [Error - 15:48:16] 2025年4月3日 15:48:15 FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [117] Unresolved requirement: Require-Bundle: org.jacoco.core; bundle-version="0.8.12" -> Bundle-SymbolicName: org.jacoco.core; bundle-version="0.8.12.202403310830" org.jacoco.core [116] Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.7.0,9.8.0)"
> 
> ```
> at org.eclipse.osgi.container.Module.start(Module.java:495)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2111)
> at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:146)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2102)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2042)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:2004)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1916)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
> ```

我也是下载的最近的java的extension pack。

**Comment by iHowCool** [comment]
> > 我的Test图标也没有，我发现启动的时候有如下的报错。
> > <img alt="Image" width="271" src="https://private-user-images.githubusercontent.com/98109964/429837298-7a3b073c-3304-42e6-8b50-42f7f1c59948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2NjY5MzIsIm5iZiI6MTc0MzY2NjYzMiwicGF0aCI6Ii85ODEwOTk2NC80Mjk4MzcyOTgtN2EzYjA3M2MtMzMwNC00MmU2LThiNTAtNDJmN2YxYzU5OTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAzVDA3NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjhjODk4OTQ1MDdlMjIxODUyYmQzMGRlNjM4NjI5YzJlNzJjZDRlNWI4N2U5MDY0MzNjYTU2MDQ0NWFjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.emO1Acm3SlqcNS14CbwGK-8Y5ZZEEzucrgvVbkB-z0M">
> > [Error - 15:48:16] 2025年4月3日 15:48:15 FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [117] Unresolved requirement: Require-Bundle: org.jacoco.core; bundle-version="0.8.12" -> Bundle-SymbolicName: org.jacoco.core; bundle-version="0.8.12.202403310830" org.jacoco.core [116] Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.7.0,9.8.0)"
> > ```
> > at org.eclipse.osgi.container.Module.start(Module.java:495)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2111)
> > at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:146)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2102)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2042)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:2004)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1916)
> > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> > at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> > at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
> > ```
> 
> 我也是下载的最近的java的extension pack。

<img width="1266" alt="Image" src="https://github.com/user-attachments/assets/3372692d-4b5e-49b8-8421-8eb55bc8f1ff" />
我看实际上jacoco的依赖和报错的对不上

**Comment by jdneo** [comment]
> > > 我的Test图标也没有，我发现启动的时候有如下的报错。
> > > <img alt="Image" width="271" src="https://private-user-images.githubusercontent.com/98109964/429837298-7a3b073c-3304-42e6-8b50-42f7f1c59948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2NjY5MzIsIm5iZiI6MTc0MzY2NjYzMiwicGF0aCI6Ii85ODEwOTk2NC80Mjk4MzcyOTgtN2EzYjA3M2MtMzMwNC00MmU2LThiNTAtNDJmN2YxYzU5OTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAzVDA3NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjhjODk4OTQ1MDdlMjIxODUyYmQzMGRlNjM4NjI5YzJlNzJjZDRlNWI4N2U5MDY0MzNjYTU2MDQ0NWFjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.emO1Acm3SlqcNS14CbwGK-8Y5ZZEEzucrgvVbkB-z0M">
> > > [Error - 15:48:16] 2025年4月3日 15:48:15 FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [117] Unresolved requirement: Require-Bundle: org.jacoco.core; bundle-version="0.8.12" -> Bundle-SymbolicName: org.jacoco.core; bundle-version="0.8.12.202403310830" org.jacoco.core [116] Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.7.0,9.8.0)"
> > > ```
> > > at org.eclipse.osgi.container.Module.start(Module.java:495)
> > > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2111)
> > > at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:146)
> > > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2102)
> > > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2042)
> > > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:2004)
> > > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1916)
> > > at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> > > at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
> > > at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
> > > ```
> > 
> > 
> > 我也是下载的最近的java的extension pack。
> 
> <img alt="Image" width="1266" src="https://private-user-images.githubusercontent.com/98109964/429842828-3372692d-4b5e-49b8-8421-8eb55bc8f1ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2Njc4NTQsIm5iZiI6MTc0MzY2NzU1NCwicGF0aCI6Ii85ODEwOTk2NC80Mjk4NDI4MjgtMzM3MjY5MmQtNGI1ZS00OWI4LTg0MjEtOGViNTViYzhmMWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAzVDA4MDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5Y2Q1MzcyNmE3NzJlMWJmODI5YmZjYzQzODM1MmZmNTNjNmE2N2FlMjIzMDMzODQzMGNiYTNlYTgxYTZjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f2_8v9HrdkpvI2ZabZb-WrIGfpc4Eutg9IMShAXw1CA"> 我看实际上jacoco的依赖和报错的对不上

Please update the test runner extension (either the stable or pre-release)

**Comment by iHowCool** [comment]
<img width="846" alt="Image" src="https://github.com/user-attachments/assets/c6cac846-9bbf-437d-9bb0-a65f03fb2251" /> it works now . GREAT !! 


add for people who use trae(the ide developed by bytedance).you can download the lastest version of extension in vscode and install manually.

<img width="819" alt="Image" src="https://github.com/user-attachments/assets/77ab6ab0-f824-4650-b7fa-53a4066875f3" />

**Comment by kathyrollo** [comment]
Do not listen to the AI. This is the solution that worked for me:

https://github.com/redhat-developer/vscode-java/issues/4396#issuecomment-4806513262

**Comment by wenytang-ms** [comment]
The compatible fix requires both sides to be updated:

`redhat.java` `1.55.0` or newer
`Test Runner for Java` `0.46.0` or newer

`redhat.java` 1.55.0 contains the JDT-LS/JDT fix, and `Test Runner for Java` 0.46.0 contains the matching fixes for test discovery and bundled JUnit/ASM dependencies. I verified this combination with a plain Eclipse Java project using `junit-platform-console-standalone-1.13.4.jar`, and the JUnit 5 tests were discovered correctly.

**Comment by desmondc9** [comment]
**Minimal reproduction** — I can reproduce this deterministically with a bare-bones Maven project, and the trigger is a single flag: `--enable-preview` in `maven-compiler-plugin`.

**Environment**

- eclipse.jdt.ls `1.60.0` (202606262232), java-test plugin `0.43.1` (loaded via `initOptions.bundles`)
- JDK 21.0.2 running the LS, matching the project's `<release>21</release>`
- Observed from **Neovim (nvim-jdtls)** calling the same LSP commands VS Code uses — confirming this is server-side and client-independent

**Steps**

1. Create a project with this `pom.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>preview-repro</artifactId>
  <version>1.0.0</version>
  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.11.4</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>21</source>
          <target>21</target>
          <release>21</release>
          <compilerArgs>
            <arg>--enable-preview</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

and `src/test/java/com/example/MiniTest.java`:

```java
package com.example;

import org.junit.jupiter.api.Test;

public class MiniTest {
    @Test
    public void testOne() {
        System.out.println("one");
    }

    @Test
    public void testTwo() {
        System.out.println("two");
    }
}
```

2. Open the project and wait for the Maven import to finish. `vscode.java.test.findTestTypesAndMethods` returns `[]` — an empty result, **not** an error. No test lenses, nothing in the Test Explorer.

3. Remove **only** the `<compilerArgs><arg>--enable-preview</arg></compilerArgs>` block (change nothing else) and re-import. Tests are discovered immediately, with correct method-level items (`testLevel = 6`).

**What still works with preview enabled** (which is what makes this confusing to diagnose):

- `vscode.java.test.resolvePath` correctly reports the test source folder/package (`testLevel = 4`)
- `java.project.isTestFile` returns `true`
- The test classpath resolves fine (junit-jupiter 5.11.4 present) and the test file shows **0 problems**
- Hover on `@Test` resolves the annotation and shows its Javadoc

**Where it breaks** (from inspecting `com.microsoft.java.test.plugin-0.43.1` and the `org.eclipse.jdt.junit.core` bundle shipped with jdt.ls): `TestSearchUtils.findTestTypesAndMethods` → `JUnit5TestSearcher.isTestClass` → `JUnit5TestFinder.isTest(type)` → `ASTParser.setProject(...)` + `createBindings(...)` yields no usable binding when the project options have `enablePreviewFeatures=enabled`, so `isTest` returns `false` for every type, the searcher gets filtered out, and the handler returns an empty list. This matches the error already quoted in this issue ("Preview features enabled at an invalid source release level 21, preview can be enabled only at source level 22") — ECJ only accepts preview at its latest supported source level, and on this code path the rejection silently degrades to "no tests found" instead of surfacing an error.

`vscode.java.test.findTestPackagesAndTypes` returns `[]` for the same reason, so the Test Explorer stays empty project-wide.

Since `--enable-preview` combined with a fixed `--release` is a documented, supported Maven configuration, test discovery shouldn't silently return empty in this setup. A cleaner failure (e.g., surfacing the ECJ preview error) would already make this much easier to hit-diagnose. Thanks!

---

**Update (2026-09-22): re-tested with the latest published components on both sides — the Maven path is still broken.**

Following @wenytang-ms's comment above, I re-ran the minimal repro with the newest available pieces:

- eclipse.jdt.ls **1.61.0** (`1.61.0.202609031315`, the 2026-09-03 milestone — two months after the fix shipped in redhat.java 1.55.0)
- Test Runner **0.46.0** (current marketplace build; note that both marketplace builds I checked bundle server plugin `com.microsoft.java.test.plugin` `0.43.1` — the plugin jar itself does not appear to have been republished)

Result:

| Scenario | `vscode.java.test.findTestTypesAndMethods` |
|---|---|
| same project, `--enable-preview` removed (control) | ✅ tests discovered on first attempt after import (`testLevel = 6` items) |
| with `<compilerArgs><arg>--enable-preview</arg></compilerArgs>` | ❌ returns `[]`, retried 6× over ~90s after `initialization job finished` |

So the fix combination appears to cover the scenario it was verified with — a plain Eclipse-format project where preview is enabled via Eclipse project settings — but **not** Maven projects, where m2e maps `--enable-preview` from `maven-compiler-plugin` `<compilerArgs>` into the JDT project options.

To help narrow it down: with preview enabled, `vscode.java.test.resolvePath` still reports the test package correctly (`testLevel = 4`), `java.project.isTestFile` returns `true`, the file reconciles with 0 problems, and hover on `@Test` resolves with full Javadoc — only the `ASTParser`-binding-based test item resolution silently returns nothing.

**Comment by wenytang-ms** [comment]
Thanks for the detailed minimal reproduction and the retest. I traced the server-side failure and opened #1938 with a fix for the test-discovery path.

With JDT's project options at `source=21, preview=enabled`, the discovery AST reports `PreviewFeaturesNotAllowed` (the JDT version tested accepts preview only for its latest source level). In `findTestTypesAndMethods`, `TypeDeclaration.resolveBinding()` then returns `null`, and the extension returns `[]` **before it reaches `JUnit5TestFinder`**. The PR retries discovery using a parser-local preview-disabled option when the source level is older than JDT's latest, without changing project settings or the `--enable-preview` test launch argument. It also covers project-wide discovery/nested tests and surfaces a diagnostic if bindings still cannot be resolved.

I verified the behavior in an isolated VS Code extension host (JDK 21, JDT LS 1.61.0, Test Runner 0.46.0) with JDT preview explicitly enabled; the control without preview also works. One caveat: on my machine the Maven `compilerArgs` in your POM *alone* did not turn on the JDT preview project option, so I have not independently reproduced that Maven-to-JDT import step. The new Tycho regression test also could not run locally because the target-platform build fails with missing JDT types. The PR is open for review; I am leaving this issue open until the fix is validated against your Maven setup and released.
