### ISSUE TITLE
Get error when first running the test

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-test#256]
log:

`Failed to load the test config! Please check whether your test configuration is a valid JSON file. Details: Unexpected end of JSON input.`

call stack:
```
Error: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at fs.readFile (C:\Users\xxx\.vscode\extensions\vscjava.vscode-java-test-0.7.1\out\src\testConfigManager.js:40:45)
	at C:\Users\xxx\.vscode\extensions\vscjava.vscode-maven-0.9.2\node_modules\async-listener\glue.js:188:31
	at tryToString (fs.js:449:3)
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by jdneo** [comment]
Closing it since I cannot repro this issue again in 0.8.0.
