### ISSUE TITLE
Will run all tests of outer class when trigger inner class in test explorer

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#411]
Normal when triggering the test of inner class in a test file
But when trigger inner class in test explorer, it will run all tests including other methods under the outer class
![image](https://user-images.githubusercontent.com/22470312/48122543-be538200-e2b2-11e8-9de0-128ce969be1a.png)

**Comment by jdneo** [comment]
There is another issue here:

I tested the inner class case in a TestNG project, the TestNG runner cannot find the classpath, which says:
```
[ERROR] org.testng.TestNGException: 
Cannot find class in classpath: com.mkyong.testng.examples.suite.TestDatabase.InnerClass
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:81)
	at org.testng.xml.XmlClass.init(XmlClass.java:73)
	at org.testng.xml.XmlClass.init(XmlClass.java:63)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:39)
	at com.microsoft.java.test.runner.testng.TestNGRunner.createClass(TestNGRunner.java:52)
	at com.microsoft.java.test.runner.testng.TestNGRunner.createTests(TestNGRunner.java:46)
	at com.microsoft.java.test.runner.testng.TestNGRunner.run(TestNGRunner.java:31)
	at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:32)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53).
```

**Comment by bsaby** [comment]
And also find that if running test from the outer class code lens, the inner class tests  will not be run
