### ISSUE TITLE
Unit tests "abstract" classes not recognized

### ISSUE THREAD

**Issue by ppatierno** [Microsoft/vscode-java-test#575]
Hello I have a project with an abstract class containing some JUnit tests and an abstract method.
Then I have another class deriving from the first one implementing that method.
I see that the java test extention don't recognize these classes as valid for running tests.
I mean, their methods are showed in the tests lists but in the source code file, the "Run Test | Debug Test" isn't showed.
If I try to run them I got the following exception for every test:

```
Message:

null
Stack trace:

java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at io.vertx.ext.unit.junit.VertxUnitRunner.methodBlock(VertxUnitRunner.java:152)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:196)
	at io.vertx.ext.unit.junit.VertxUnitRunner$3.evaluate(VertxUnitRunner.java:211)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.microsoft.java.test.runner.junit4.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at com.microsoft.java.test.runner.junit4.CustomizedJUnit4CoreRunner.run(CustomizedJUnit4CoreRunner.java:45)
	at com.microsoft.java.test.runner.junit4.JUnit4Launcher.execute(JUnit4Launcher.java:30)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:53)
```

In order to have these class recognized I have to remove the "abstract".

All the tests run fine under IntelliJ. Is it a limitation of this Java test plugin?

**Comment by jdneo** [comment]
Dup with #435
