### ISSUE TITLE
NPE occur when expanding the default package

### ISSUE THREAD

**Issue by mccreery** [microsoft/vscode-java-test#611]
I have a very simple Gradle (5.1.1) project with JUnit 4 tests configured in my `build.gradle`. The resulting `.classpath` file used by Eclipse JDT contains the following entries:<details>
<summary>Eclipse <code>.classpath</code> entries</summary>

```xml
<classpathentry kind="src" output="bin/main" path="src/main/java">
    <attributes>
        <attribute name="gradle_scope" value="main"/>
        <attribute name="gradle_used_by_scope" value="main,test"/>
    </attributes>
</classpathentry>
<classpathentry kind="src" output="bin/test" path="src/test/java">
    <attributes>
        <attribute name="gradle_scope" value="test"/>
        <attribute name="gradle_used_by_scope" value="test"/>
        <attribute name="test" value="true"/>
    </attributes>
</classpathentry>
```
</details>

(I added the `"test"` attribute to the test entry manually, as per #470.)

Everything is compiled correctly and the VS Code Problems view is empty. However, when I try to load my tests (just one class, `src/test/java/Tests.java`) into the test explorer, I reach a `NullPointerException` from [this line](https://github.com/Microsoft/vscode-java-test/blob/master/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java#L294):
<details>
<summary>NPE Stacktrace</summary>

```
java.lang.NullPointerException
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchInPackage(TestSearchUtils.java:294)
	at com.microsoft.java.test.plugin.util.TestSearchUtils.searchTestItems(TestSearchUtils.java:133)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:152)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:142)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:451)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:793)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
</details>

It seems like [`resolvePackage`](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java#L166) can and does return `null`, but this plugin does not check for `null`.

## Code
<details>
<summary><code>src/test/java/Tests.java</code></summary>

```java
import org.junit.Assert;
import org.junit.Test;

public class Tests {
    @Test
    public void testA() {
        Assert.assertTrue(true);
    }
}
```
</details>
<details>
<summary><code>build.gradle</code></summary>

```groovy
apply plugin: 'java'
apply plugin: 'eclipse'

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.12'
}
```
</details>

## Reproduction
Just create a Gradle 5.1.1 (should still happen on other versions) project with the above code and populate the test explorer, then try to expand the empty entry under the root project. Mine looks like this:
![Test Explorer view](https://user-images.githubusercontent.com/4602020/52536529-b7298d80-2d53-11e9-8373-a68d5238cf37.png)

**Comment by jdneo** [comment]
@mccreery Thank you for reporting, will take a look

**Comment by jdneo** [comment]
@mccreery For now the extension does not support the `default` package. I'll figure out if there is any way to support it.

**Comment by mccreery** [comment]
Using a package is a good fix for the time being, thanks.

**Comment by suiwenfeng** [comment]
add eclipse to gradle plugins, and then `gradle eclipse`, .classpath will generated and recognized by vscode.
