### ISSUE TITLE
NPE when invoking test with codelens or test explorer

### ISSUE THREAD

**Issue by Nukepayload2** [microsoft/vscode-java-test#682]
Our tests can be executed with eclipse oxygen with the testng plugin. But when I try to run tests with vscode, tests won't run, and vscode shows a notification "Error". I've tried to remove "%AppData%\Code\User\workspaceStorage" and restart vscode. It didn't solve my problem.

Java test runner version: 0.16.0
JDK version: 8u201

.classpath file
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src">
		<attributes>
			<attribute name="test" value="true"/>
			<attribute name="source_encoding" value="UTF-8"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="lib" path="lib/testng-6.8.jar"/>
	<classpathentry combineaccessrules="false" kind="src" path="/TheProjectToBeTested"/>
</classpath>
```
Java test runner log 
```json
{"message":"Error.","level":"error"}
```
Output of "Language support for Java"
```
[Error - 4:43:59 PM] Apr 29, 2019 4:43:59 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.NullPointerException
	at com.microsoft.java.test.plugin.util.ProjectUtils.lambda$6(ProjectUtils.java:128)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.microsoft.java.test.plugin.util.ProjectUtils.getTestOutputPath(ProjectUtils.java:131)
	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveRuntimeClassPath(RuntimeClassPathUtils.java:67)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:42)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:439)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$33(JDTLanguageServer.java:835)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[Error - 4:43:59 PM] Apr 29, 2019 4:43:59 PM Error in calling delegate command handler
null
java.lang.NullPointerException
	at com.microsoft.java.test.plugin.util.ProjectUtils.lambda$6(ProjectUtils.java:128)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.microsoft.java.test.plugin.util.ProjectUtils.getTestOutputPath(ProjectUtils.java:131)
	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveRuntimeClassPath(RuntimeClassPathUtils.java:67)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:42)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:439)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$33(JDTLanguageServer.java:835)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jdneo** [comment]
Are you using default package?

**Comment by Nukepayload2** [comment]
@jdneo 
No, all test classes have package names. We are migrating our C# MSTest projects to Java testng. So, some names of the packages have capital characters, and they are not start with `com.` or `org.` . Does the naming convention violation cause this bug?

**Comment by jdneo** [comment]
@Nukepayload2 is it possible for you to share a sample project which can repro this issue to us?

**Comment by Nukepayload2** [comment]
@jdneo I can't reproduce this issue after upgrading vscode to `1.34.0` .
