### ISSUE TITLE
Error: parameter '-port' not specified when Debug JUnit Plugin-in Test

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode-java-test#879]
When running the test of [`eclipse.jdt.ls`](https://github.com/eclipse/eclipse.jdt.ls) in vscode test runner using `Debug JUnit Plugin-in Test`, the following error occured:

```
java.lang.IllegalArgumentException: Error: parameter '-port' not specified
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:356)
        at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.init(RemotePluginTestRunner.java:264)
        at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:161)
        at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:27)
        at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:57)
        at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:49)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

Seems that it's related to #834, and after reverting back from 
```ts
    const portIndex: number = junitLaunchArgs.programArguments.indexOf('-port');
    if (portIndex > -1 && junitLaunchArgs.programArguments.length > portIndex + 1) {
        junitLaunchArgs.programArguments[portIndex + 1] = `${socketPort}`;
    }
```
to
```ts
    junitLaunchArgs.programArguments.push('-port', `${socketPort}`);
```
~~The debug session can then be started normally. Seems that if the `programArguments` contains no `'-port'`, the client will also not add `socketPort` for it.~~ Investigating

**Comment by jdneo** [comment]
Have fixed in https://github.com/microsoft/vscode-java-test/pull/875

Please wait for next release or downgrade to 0.20.0 as a workaround
