### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by shanewaz-abbas** [microsoft/vscode-java-test#972]
```
java.lang.NoClassDefFoundError: org/junit/platform/commons/PreconditionViolationException
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createFilteredTest(JUnit5TestLoader.java:70)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:64)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:53)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.PreconditionViolationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 7 more
```

I have no clue why its happening. It's my first time trying to run tests for Java. Its a spring boot project, is there a way I can run the tests from command line instead

**Comment by jdneo** [comment]
What does your test dependencies look like? Is it possible to provide a sample project to us to diagnostic?

**Comment by shanewaz-abbas** [comment]
@jdneo Here's the important parts::
```
junitVersion = '5.3.1'
mockitoVersion = '2.23.4'
```

```
dependencies {
    testImplementation "org.mockito:mockito-junit-jupiter:$mockitoVersion"
    testImplementation "org.junit.jupiter:junit-jupiter-migrationsupport:$junitVersion"
```

![image](https://user-images.githubusercontent.com/61433809/78696002-3a515f80-78d5-11ea-9955-0f4c49e598f3.png)

**Comment by jdneo** [comment]
How about just simply use:

```
dependencies {
	testImplementation('org.junit.jupiter:junit-jupiter:5.6.1')
}
```

**Comment by shanewaz-abbas** [comment]
I tried that and still the same error

**Comment by shanewaz-abbas** [comment]
I tried in the command line and then it runs the tests properly:

` ./gradlew test

**Comment by jdneo** [comment]
I'm using [this project](https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle) and change the dependency to:

```
dependencies {
	testImplementation('org.junit.jupiter:junit-jupiter:5.6.2')
	testImplementation('org.junit.jupiter:junit-jupiter-migrationsupport:5.6.2')
}
```

Not able to repro this issue.

**Comment by jdneo** [comment]
@shanewaz-abbas Hi, please let me know if the problem is still occur or not. You can also share a sample project to us if you want.

**Comment by shanewaz-abbas** [comment]
@jdneo I was able to finally figure out how to solve it:
```
-    testImplementation "org.mockito:mockito-junit-jupiter:$mockitoVersion"
-    testImplementation "org.junit.jupiter:junit-jupiter-migrationsupport:$junitVersion"
+    testImplementation "org.mockito:mockito-junit-jupiter"
+    testImplementation "org.junit.jupiter:junit-jupiter-migrationsupport:5.6.2"
+    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
```

I don't why that worked but I'm glad there is a solution at least.

**Comment by jdneo** [comment]
Good to know problem solved!
