### ISSUE TITLE
NoClassDefFoundError triggered when trying to run a Junit 4 test

### ISSUE THREAD

**Issue by bootFyre17** [microsoft/vscode-java-test#973]
Currently getting the current exception when trying to run or debug a JUnit 4 test:

java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
Class.java:264
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadTestLoaderClass(RemoteTestRunner.java:381)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
URLClassLoader.java:382
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
ClassLoader.java:424
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
Launcher.java:349
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
ClassLoader.java:357
	... 8 more

VSCode Info: 
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

OpenJDK8

**Comment by bootFyre17** [comment]
I found my configuration error...apparently my .project file had both gradle and maven natures added which must have been colliding with each other in some way...removing the maven nature fixed the issue.
