### ISSUE TITLE
Junit 5 cannot test the files in directory whose name contains Chinese characters

### ISSUE THREAD

**Issue by gdjs2** [microsoft/vscode-java-test#977]
When I click Run Test it will show Error: The resource: /Volumes/***/���/***/***.java is not testable. where the ??? is the position of original Chinese characters. This problem occurs both under windows and macOS.

**Comment by AndreasLepik** [comment]
I had the same problem when my project had a parent directory containing 'ä'. Testing worked when I moved the project elsewhere.

**Comment by modyuan** [comment]
same problem.
the output is 
```
Error: The resource: /Users/yuan/��/�\:/test-maven/testMaven/src/test/java/com/yzmoe/TestJava.java is not testable..
```

**Comment by qinlinwang** [comment]
I had the same problem when my project‘ directory is `~/文档/myproject/demo`. If I run the test, output is "Error: Running the contributed command: 'java.execute.workspaceCommand' failed..". And the output in `Java:Open Java Language Server Log File` is:

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2021-08-01 15:04:06.676
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.IllegalArgumentException: Bad escape
	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:103)
	at java.base/java.nio.file.Path.of(Path.java:203)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at com.microsoft.java.test.plugin.launchers.JUnitLaunchUtils.resolveLaunchArgument(JUnitLaunchUtils.java:90)
	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:54)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:505)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

When I change the project directory to `~/myproject/demo`, it works well.
Here is my environment:
```
    The version of VS Code: 1.58.2
    Your operating system : Debian 10
```

**Comment by jdneo** [comment]
This should be an upstream issue: https://github.com/microsoft/vscode-java-debug/issues/622

**Comment by jdneo** [comment]
For anyone who encountered this problem, please make sure the latest [vscode java debugger](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) is installed and follow [this instruction](https://github.com/microsoft/vscode-java-debug/blob/main/Troubleshooting_encoding.md) if you still have the encoding related issue.
